input {
  beats {
    port => 5044
  }
}

filter {
  if [event][module] == "apache" and [fileset][name] == "access" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
  }

  if [event][module] == "apache" and [fileset][name] == "error" {
    grok {
      match => {
        "message" => "\\[%{DAY} %{MONTH} %{MONTHDAY} %{TIME} %{YEAR}\\] \\[%{LOGLEVEL:log.level}\\] (\\[client %{IPORHOST:source.address}\\] )?%{GREEDYDATA:error.message}"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://127.0.0.1:9200"]
    index => "logstash-apache-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
